### ISSUE TITLE
What is the canonical import path of this Go package?

### ISSUE THREAD

**Issue by dmitshur** [sourcegraph/gen-mocks#2]
I see no way of knowing if it's `github.com/sourcegraph/gen-mocks` or `sourcegraph.com/sourcegraph/gen-mocks` because it's not specified as import path comment nor in a README.

Can you please add an import path comment to resolve the ambiguity? /cc @samertm

``` Go
// Command gen-mocks ...
package main // import "..."
```

**Comment by samertm** [comment]
Thanks!

**Comment by dmitshur** [comment]
Thank you!
